[2013-10-31 12:43:18] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:14] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:34] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:54] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:59] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:45:13] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:52:34] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:52:38] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:53:18] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:53:35] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:53:41] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:58:21] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:58:37] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:10:55] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:00] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:02] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:10] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:13] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:28] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:29] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:29] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:29] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:39:06] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 15:51:06] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 16:15:21] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 16:16:14] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:16:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:16:46] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:17:00] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:17:24] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:17:28] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:23:59] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:06] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:11] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:20] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:26] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:31] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:35] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:56] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:25:39] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:25:42] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:25:47] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-03 14:01:43] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-03 18:23:47] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 09:07:02] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:14:10] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:14:13] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:14:16] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:39:53] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:40:02] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:50:21] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scms.table_name' doesn't exist' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:52:57] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:53:00] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:58:40] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usernamed' in 'field list'' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:59:37] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:59:43] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scms.sdcms_users' doesn't exist' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 20:46:51] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 20:46:56] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:57
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(57): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 21:28:40] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:75
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(75): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(23): Application\Model\User->update()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 09:08:33] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:19:31] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:21:23] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:21:27] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:36:24] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:36:30] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 10:15:09] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: parameter was not defined' in D:\localroot\framework\Application\Model\User.php:136
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(136): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:15:38] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: parameter was not defined' in D:\localroot\framework\Application\Model\User.php:138
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(138): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:16:53] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\localroot\framework\Application\Model\User.php:138
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(138): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:17:06] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\localroot\framework\Application\Model\User.php:140
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(140): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:17:23] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\localroot\framework\Application\Model\User.php:140
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(140): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:18:23] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 'test'' at line 1' in D:\localroot\framework\Application\Model\User.php:140
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(140): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:18:55] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'username'' in D:\localroot\framework\Application\Model\User.php:58
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(58): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(27): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:20:47] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'username'' in D:\localroot\framework\Application\Model\User.php:58
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(58): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(27): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 14:35:56] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'Parameter should be an array! Got: boolean' in D:\localroot\framework\System\Framework\Form\FormHandler.php:27
Stack trace:
#0 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): System\Framework\Form\FormHandler->getFields(true)
#1 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#3 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-05 20:38:19] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:38:19] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:38:57] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:27] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:33] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:36] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:41] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:46] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:55] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:40:00] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php:21
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php(21): PDO->__construct('mysql:dbname=sc...', 'root', '')
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Model.php(16): System\Framework\Database\Database->__construct()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Model/Auth.php(15): System\Framework\Model->getDatabase()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/LoginController.php(19): Application\Model\Auth->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\LoginController->index()
#5 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#6 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#7 {main} [] []
[2013-11-05 20:41:04] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'fail to load language file '/Applications/XAMPP/xamppfiles/htdocs/framework/System/lang/en.php'' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Form/FormValidator.php:61
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/RegisterController.php(23): System\Framework\Form\FormValidator->__construct(Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-05 20:42:00] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:42:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:42:57] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:42:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:43:04] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:43:07] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:44:40] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:45:56] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:45:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:46:05] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:46:09] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:46:50] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:47:55] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php:21
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php(21): PDO->__construct('mysql:dbname=sc...', 'root', '')
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Model.php(16): System\Framework\Database\Database->__construct()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Model/Auth.php(15): System\Framework\Model->getDatabase()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/LoginController.php(19): Application\Model\Auth->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\LoginController->index()
#5 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#6 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#7 {main} [] []
[2013-11-05 20:55:51] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php:21
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php(21): PDO->__construct('mysql:dbname=sc...', 'root', '')
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Model.php(16): System\Framework\Database\Database->__construct()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Model/Auth.php(15): System\Framework\Model->getDatabase()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/LoginController.php(19): Application\Model\Auth->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\LoginController->index()
#5 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#6 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#7 {main} [] []
[2013-11-06 13:40:32] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-06 13:40:54] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 09:39:52] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 09:39:55] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 09:40:02] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'fail to load language file 'D:\localroot\framework\System/lang/en.php'' in D:\localroot\framework\System\Framework\Form\FormValidator.php:61
Stack trace:
#0 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(24): System\Framework\Form\FormValidator->__construct(Array)
#1 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#3 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-07 09:43:05] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'Rule 'equal' has not been registered with System\Framework\Form\FormValidator::addRule().' in D:\localroot\framework\System\Framework\Form\FormValidator.php:535
Stack trace:
#0 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(27): System\Framework\Form\FormValidator->rule('equal', 'password', Array)
#1 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#3 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-07 11:53:16] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:43:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:45:16] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:46:20] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:48:39] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:04:51] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:38] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:43] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:51] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 17:22:46] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 17:22:50] Twig_Error_Loader.CRITICAL: Exception thrown: exception 'Twig_Error_Loader' with message 'Unable to find template "Core/index.html.twig" (looked into: D:\localroot\framework\System\Framework/../../Application/View).' in D:\localroot\framework\Vendor\Twig\Loader\Filesystem.php:202
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Loader\Filesystem.php(138): Twig_Loader_Filesystem->findTemplate('Core/index.html...')
#1 D:\localroot\framework\Vendor\Twig\Environment.php(265): Twig_Loader_Filesystem->getCacheKey('Core/index.html...')
#2 D:\localroot\framework\Vendor\Twig\Environment.php(312): Twig_Environment->getTemplateClass('Core/index.html...', NULL)
#3 D:\localroot\framework\Application\Cache\twig\1b\50\8d0f3b5d84240fecca6c64564cd6.php(10): Twig_Environment->loadTemplate('Core/index.html...')
#4 D:\localroot\framework\Vendor\Twig\Environment.php(334): __TwigTemplate_1b508d0f3b5d84240fecca6c64564cd6->__construct(Object(Twig_Environment))
#5 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#6 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#7 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#8 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#9 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#10 {main} [] []
[2013-11-07 17:23:06] Twig_Error_Syntax.CRITICAL: Exception thrown: exception 'Twig_Error_Syntax' with message 'Unknown tag name "stylesheets" in "Core/default.html.twig" at line 11' in D:\localroot\framework\Vendor\Twig\Parser.php:186
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Parser.php(99): Twig_Parser->subparse(NULL, false)
#1 D:\localroot\framework\Vendor\Twig\Environment.php(479): Twig_Parser->parse(Object(Twig_TokenStream))
#2 D:\localroot\framework\Vendor\Twig\Environment.php(529): Twig_Environment->parse(Object(Twig_TokenStream))
#3 D:\localroot\framework\Vendor\Twig\Environment.php(323): Twig_Environment->compileSource('<!DOCTYPE html ...', 'Core/default.ht...')
#4 D:\localroot\framework\Application\Cache\twig\1b\50\8d0f3b5d84240fecca6c64564cd6.php(10): Twig_Environment->loadTemplate('Core/default.ht...')
#5 D:\localroot\framework\Vendor\Twig\Environment.php(334): __TwigTemplate_1b508d0f3b5d84240fecca6c64564cd6->__construct(Object(Twig_Environment))
#6 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#7 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#8 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#9 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#10 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#11 {main} [] []
[2013-11-07 17:24:46] Twig_Error_Syntax.CRITICAL: Exception thrown: exception 'Twig_Error_Syntax' with message 'Unknown tag name "stylesheets" in "Core/default.html.twig" at line 11' in D:\localroot\framework\Vendor\Twig\Parser.php:186
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Parser.php(99): Twig_Parser->subparse(NULL, false)
#1 D:\localroot\framework\Vendor\Twig\Environment.php(479): Twig_Parser->parse(Object(Twig_TokenStream))
#2 D:\localroot\framework\Vendor\Twig\Environment.php(529): Twig_Environment->parse(Object(Twig_TokenStream))
#3 D:\localroot\framework\Vendor\Twig\Environment.php(323): Twig_Environment->compileSource('<!DOCTYPE html ...', 'Core/default.ht...')
#4 D:\localroot\framework\Application\Cache\twig\1b\50\8d0f3b5d84240fecca6c64564cd6.php(10): Twig_Environment->loadTemplate('Core/default.ht...')
#5 D:\localroot\framework\Vendor\Twig\Environment.php(334): __TwigTemplate_1b508d0f3b5d84240fecca6c64564cd6->__construct(Object(Twig_Environment))
#6 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#7 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#8 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#9 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#10 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#11 {main} [] []
[2013-11-08 14:12:30] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-08 14:12:48] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-11 12:18:41] Twig_Error_Syntax.CRITICAL: Exception thrown: exception 'Twig_Error_Syntax' with message 'Unknown tag name "extends" in "Home/index.html.twig" at line 1' in D:\localroot\framework\Vendor\Twig\Parser.php:186
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Parser.php(99): Twig_Parser->subparse(NULL, false)
#1 D:\localroot\framework\Vendor\Twig\Environment.php(479): Twig_Parser->parse(Object(Twig_TokenStream))
#2 D:\localroot\framework\Vendor\Twig\Environment.php(529): Twig_Environment->parse(Object(Twig_TokenStream))
#3 D:\localroot\framework\Vendor\Twig\Environment.php(323): Twig_Environment->compileSource('{% extends 'Cor...', 'Home/index.html...')
#4 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#5 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#6 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#7 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#8 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#9 {main} [] []
[2013-11-11 12:19:28] Twig_Error_Syntax.CRITICAL: Exception thrown: exception 'Twig_Error_Syntax' with message 'Unknown tag name "extends" in "Home/index.html.twig" at line 1' in D:\localroot\framework\Vendor\Twig\Parser.php:186
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Parser.php(99): Twig_Parser->subparse(NULL, false)
#1 D:\localroot\framework\Vendor\Twig\Environment.php(479): Twig_Parser->parse(Object(Twig_TokenStream))
#2 D:\localroot\framework\Vendor\Twig\Environment.php(529): Twig_Environment->parse(Object(Twig_TokenStream))
#3 D:\localroot\framework\Vendor\Twig\Environment.php(323): Twig_Environment->compileSource('{% extends 'Cor...', 'Home/index.html...')
#4 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#5 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#6 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#7 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#8 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#9 {main} [] []
[2013-11-11 12:19:47] Twig_Error_Syntax.CRITICAL: Exception thrown: exception 'Twig_Error_Syntax' with message 'Unknown tag name "extends" in "Home/index.html.twig" at line 1' in D:\localroot\framework\Vendor\Twig\Parser.php:186
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Parser.php(99): Twig_Parser->subparse(NULL, false)
#1 D:\localroot\framework\Vendor\Twig\Environment.php(479): Twig_Parser->parse(Object(Twig_TokenStream))
#2 D:\localroot\framework\Vendor\Twig\Environment.php(529): Twig_Environment->parse(Object(Twig_TokenStream))
#3 D:\localroot\framework\Vendor\Twig\Environment.php(323): Twig_Environment->compileSource('{% extends 'Cor...', 'Home/index.html...')
#4 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#5 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#6 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#7 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#8 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#9 {main} [] []
[2013-11-11 12:59:08] Twig_Error_Syntax.CRITICAL: Exception thrown: exception 'Twig_Error_Syntax' with message 'Unclosed "(" in "Core/default.html.twig" at line 23' in D:\localroot\framework\Vendor\Twig\Lexer.php:267
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Lexer.php(219): Twig_Lexer->lexExpression()
#1 D:\localroot\framework\Vendor\Twig\Lexer.php(118): Twig_Lexer->lexVar()
#2 D:\localroot\framework\Vendor\Twig\Environment.php(443): Twig_Lexer->tokenize('<!DOCTYPE html ...', 'Core/default.ht...')
#3 D:\localroot\framework\Vendor\Twig\Environment.php(529): Twig_Environment->tokenize('<!DOCTYPE html ...', 'Core/default.ht...')
#4 D:\localroot\framework\Vendor\Twig\Environment.php(323): Twig_Environment->compileSource('<!DOCTYPE html ...', 'Core/default.ht...')
#5 D:\localroot\framework\Application\Cache\twig\1b\50\8d0f3b5d84240fecca6c64564cd6.php(10): Twig_Environment->loadTemplate('Core/default.ht...')
#6 D:\localroot\framework\Vendor\Twig\Environment.php(334): __TwigTemplate_1b508d0f3b5d84240fecca6c64564cd6->__construct(Object(Twig_Environment))
#7 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Environment->loadTemplate('Home/index.html...')
#8 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#9 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#10 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#11 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#12 {main} [] []
[2013-11-11 12:59:16] Twig_Error_Runtime.CRITICAL: Exception thrown: exception 'Exception' with message 'Route home not found!' in D:\localroot\framework\System\Framework\HTTP\Response.php:57
Stack trace:
#0 D:\localroot\framework\System\Framework\Template\Extension\CoreExtension.php(21): System\Framework\HTTP\Response->url('home')
#1 [internal function]: System\Framework\Template\Extension\CoreExtension->System\Framework\Template\Extension\{closure}('home')
#2 D:\localroot\framework\Application\Cache\twig\15\2b\88eafbd883225dffe80c031aa922.php(48): call_user_func_array(Object(Closure), Array)
#3 D:\localroot\framework\Vendor\Twig\Template.php(264): __TwigTemplate_152b88eafbd883225dffe80c031aa922->doDisplay(Array, Array)
#4 D:\localroot\framework\Vendor\Twig\Template.php(238): Twig_Template->displayWithErrorHandling(Array, Array)
#5 D:\localroot\framework\Application\Cache\twig\1b\50\8d0f3b5d84240fecca6c64564cd6.php(24): Twig_Template->display(Array, Array)
#6 D:\localroot\framework\Vendor\Twig\Template.php(264): __TwigTemplate_1b508d0f3b5d84240fecca6c64564cd6->doDisplay(Array, Array)
#7 D:\localroot\framework\Vendor\Twig\Template.php(238): Twig_Template->displayWithErrorHandling(Array, Array)
#8 D:\localroot\framework\Vendor\Twig\Template.php(249): Twig_Template->display(Array)
#9 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Template->render(Array)
#10 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#11 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#12 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#13 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#14 {main}

Next exception 'Twig_Error_Runtime' with message 'An exception has been thrown during the rendering of a template ("Route home not found!") in "Home/index.html.twig".' in D:\localroot\framework\Vendor\Twig\Template.php:279
Stack trace:
#0 D:\localroot\framework\Vendor\Twig\Template.php(238): Twig_Template->displayWithErrorHandling(Array, Array)
#1 D:\localroot\framework\Application\Cache\twig\1b\50\8d0f3b5d84240fecca6c64564cd6.php(24): Twig_Template->display(Array, Array)
#2 D:\localroot\framework\Vendor\Twig\Template.php(264): __TwigTemplate_1b508d0f3b5d84240fecca6c64564cd6->doDisplay(Array, Array)
#3 D:\localroot\framework\Vendor\Twig\Template.php(238): Twig_Template->displayWithErrorHandling(Array, Array)
#4 D:\localroot\framework\Vendor\Twig\Template.php(249): Twig_Template->display(Array)
#5 D:\localroot\framework\Vendor\Twig\Environment.php(288): Twig_Template->render(Array)
#6 D:\localroot\framework\Application\Controller\Home\HomeController.php(11): Twig_Environment->render('Home/index.html...', Array)
#7 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Home\HomeController->index()
#8 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#9 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#10 {main} [] []
[2013-11-11 12:59:49] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-11 12:59:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-11 13:00:01] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
